.name: Build and Test ASP.NET # The name of the workflow

on: # Specifies the events that trigger the workflow
  push: # Trigger the workflow on push events
    branches:
      - main # Only trigger on pushes to the main branch
  pull_request: # Trigger the workflow on pull request events
    branches:
      - main # Only trigger on pull requests to the main branch

jobs: # Defines the jobs to be run
  build: # The name of the job
    runs-on: ubuntu-latest # The job will run on the latest version of Ubuntu

    steps: # The steps to be executed in the job
    - name: Checkout code # Step to check out the code from the repository
      uses: actions/checkout@v2 # Uses the checkout action to clone the repository

    - name: Setup .NET # Step to set up the .NET environment
      uses: actions/setup-dotnet@v3 # Uses the setup-dotnet action
      with:
        dotnet-version: '8.0' # Specifies the .NET version to use

    - name: Restore dependencies # Step to restore the project's dependencies
      run: dotnet restore # Runs the dotnet restore command

    - name: Build # Step to build the project
      run: dotnet build --no-restore -o out # Runs the dotnet build command without restoring dependencies again

    - name: Test # Step to run tests
      run: dotnet test --no-build --verbosity normal # Runs the dotnet test command without building the project again

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        # Artifact name
        name: DemoWebApp
        # A file, directory or wildcard pattern that describes what to upload
        path: ./out/

  deploy:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: DemoWebApp
          path: .
